### ISSUE TITLE
Отображать полностью длинные строки в примерах входных параметров

### ISSUE THREAD

**Issue by denis96z** [gothing/draft-front#1]
Если строка слишком длинная, она может обрезаться на узких экранах, при этом посмотреть содержимое полностью становится невозможно.

Пример:
https://github.com/denis96z/draft-front/blob/screenshot/screenshot/screenshot_01.png

**Comment by RubaXa** [comment]
Ох, только сейчас заметил, поправлю.

**Comment by RubaXa** [comment]
Готов
