### ISSUE TITLE
Поддрежка `deprecated`

### ISSUE THREAD

**Issue by RubaXa** [gothing/draft-front#14]
Добавился в gothing/draft#15 (с) @denis96z

**Comment by RubaXa** [comment]
@denis96z не сказал бы что красиво, но лучше ничего не получается

![image](https://user-images.githubusercontent.com/1109562/109643393-37063880-7b65-11eb-8fc7-79e5d2da527c.png)

**Comment by denis96z** [comment]
@RubaXa мне кажется норм выглядит
