### ISSUE TITLE
не пропадает поле omitempty

### ISSUE THREAD

**Issue by man0xff** [gothing/draft-front#4]
В структуре ответа поле указано как omitempty, внутри scheme.Case задается пример ответа, поле не инициализируется (пустая строка), но оно не пропадает в выводе godraft:doc. При этом другое поле находящееся в списке структур, с тем же тегом omitempty успешно скрывается

**Comment by RubaXa** [comment]
Fixed https://github.com/gothing/draft/releases/tag/v1.0.0-alpha.12
