### ISSUE TITLE
Поддержать Content-Type принимаемый на вход

### ISSUE THREAD

**Issue by denis96z** [gothing/draft-front#8]
**Кейс:**
Некоторое API может принимать на вход только определенный Content-Type (application/x-www-form-urlencoded), хотелось бы иметь возможность отобразить это явно в документации

**Comment by RubaXa** [comment]
А что ты имеешь в виду под явным?

**Comment by denis96z** [comment]
> А что ты имеешь в виду под явным?

Сейчас есть возможность указать метод, например POST, хочется чтобы если указано что на вход может приниматься  только определенный Content-Type, этот Content-Type отображался бы прямо в интерфейсе доки рядом с методом

**Comment by denis96z** [comment]
Для этих целей логично использовать Request Headers
https://github.com/gothing/draft/issues/9
